// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-N7VY9dd-12NBPkYMSk63fpDERTe-ALg',
    appId: '1:1085424018448:web:6f17ee94996f83615d9695',
    messagingSenderId: '1085424018448',
    projectId: 'stewardie',
    authDomain: 'stewardie.firebaseapp.com',
    storageBucket: 'stewardie.firebasestorage.app',
    measurementId: 'G-QMZDE2R3BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU-WLUpVK2KQGm9ATLOTtmqgTq5o72Gvo',
    appId: '1:1085424018448:android:a117be6c7804e1895d9695',
    messagingSenderId: '1085424018448',
    projectId: 'stewardie',
    storageBucket: 'stewardie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpXca-qqYOUx_QPXkpBgMHJ5JrYtcbKN4',
    appId: '1:1085424018448:ios:82872c3907496b7f5d9695',
    messagingSenderId: '1085424018448',
    projectId: 'stewardie',
    storageBucket: 'stewardie.firebasestorage.app',
    iosBundleId: 'dev.stewardie.demo.stewardie',
  );
}
