import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
import { decodeProtectedHeader, importX509, jwtVerify } from "https://esm.sh/jose@5.9.6";

const project = "stewardie";
const sb = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, {auth:{persistSession:false,autoRefreshToken:false}});
const bucket = sb.storage.from("moments");
const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, content-type, apikey","Access-Control-Allow-Methods":"POST, OPTIONS","Cache-Control":"no-store"};
class Failure extends Error { constructor(message:string, public status=400) {super(message);} }
let certs: Record<string,string> = {}; let certExpiry=0;
async function identify(req:Request) {
 const token=req.headers.get("authorization")?.match(/^Bearer (.+)$/i)?.[1];
 if(!token || token.length>8192) throw new Failure("Sign in again to share photos.",401);
 let header; try {header=decodeProtectedHeader(token);} catch (_) {throw new Failure("Invalid sign-in.",401);}
 const {kid,alg}=header;
 if(alg!=="RS256" || !kid) throw new Failure("Invalid sign-in.",401);
 if(Date.now()>certExpiry) {
  const res=await fetch("https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com");
  if(!res.ok) throw new Failure("Authentication is temporarily unavailable.",503);
  certs=await res.json(); certExpiry=Date.now()+Math.min(3600,Number(res.headers.get("cache-control")?.match(/max-age=(\d+)/)?.[1] ?? 300))*1000;
 }
 if(!certs[kid]) throw new Failure("Sign in again.",401);
 const key=await importX509(certs[kid],"RS256");
 let verified; try {verified=await jwtVerify(token,key,{issuer:`https://securetoken.google.com/${project}`,audience:project,algorithms:["RS256"]});} catch (_) {throw new Failure("Sign in again.",401);}
 const {payload}=verified;
 if(!payload.sub || payload.sub.length>128 || payload.email_verified!==true || typeof payload.auth_time!=="number" || payload.auth_time>Date.now()/1000+60) throw new Failure("Verify your email first.",403);
 return {uid:payload.sub,token};
}
const validId=(s:unknown):s is string=>typeof s==="string"&&/^[A-Za-z0-9_-]{1,150}$/.test(s);
function unpack(v:any):any {
 if(v===undefined)return null;
 if("stringValue" in v)return v.stringValue;
 if("booleanValue" in v)return v.booleanValue;
 if("timestampValue" in v)return v.timestampValue;
 if("integerValue" in v)return Number(v.integerValue);
 if("arrayValue" in v)return (v.arrayValue.values??[]).map(unpack);
 return null;
}
async function firestore(path:string,token:string,optional=false) {
 const res=await fetch(`https://firestore.googleapis.com/v1/projects/${project}/databases/(default)/documents/${path}`,{headers:{Authorization:`Bearer ${token}`}});
 if(res.status===404 && optional)return {};
 if(!res.ok)throw new Failure(res.status===403?"You no longer have access to this space or task.":"Could not verify space access. Try again.",res.status===403?403:503);
 const body=await res.json();return Object.fromEntries(Object.entries(body.fields??{}).map(([k,v])=>[k,unpack(v)]));
}
async function member(space:string,auth:{uid:string,token:string}) {
 if(!validId(space))throw new Failure("Invalid space.");
 const parent=await firestore(`spaces/${space}`,auth.token);
 if(!Array.isArray(parent.memberUids)||!parent.memberUids.includes(auth.uid))throw new Failure("You are no longer in this space.",403);
}
function check(result:any) {if(result.error)throw new Failure(result.error.message,400);return result.data;}
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});}
async function bounded(req:Request,max:number) {
 if(Number(req.headers.get("content-length"))>max)throw new Failure("Photo request is too large.",413);
 const reader=req.body?.getReader();if(!reader)throw new Failure("Missing request.");
 let length=0;const chunks:Uint8Array[]=[];
 while(true){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>max){await reader.cancel();throw new Failure("Photo request is too large.",413);}chunks.push(value);}
 const result=new Uint8Array(length);let offset=0;for(const c of chunks){result.set(c,offset);offset+=c.length;}return result;
}
// Only baseline JPEG generated by the app. Reject EXIF and arbitrary payloads.
function jpeg(bytes:Uint8Array,max:number,maxEdge:number){
 if(bytes.length<16||bytes.length>max||bytes[0]!==255||bytes[1]!==216||bytes.at(-2)!==255||bytes.at(-1)!==217)throw new Failure("Choose a valid JPEG photo.");
 let at=2;let size:{width:number,height:number}|null=null;
 while(at+4<bytes.length){
  if(bytes[at++]!==255)throw new Failure("Invalid photo encoding.");
  const marker=bytes[at++]; if(marker===218)break;
  const len=(bytes[at]<<8)|bytes[at+1];if(len<2||at+len>bytes.length)throw new Failure("Invalid photo encoding.");
  if(marker===225||marker===237)throw new Failure("Remove photo metadata before sharing.");
  if(marker===192){size={height:(bytes[at+3]<<8)|bytes[at+4],width:(bytes[at+5]<<8)|bytes[at+6]};}
  at+=len;
 }
 if(!size||size.width<1||size.height<1||size.width>maxEdge||size.height>maxEdge)throw new Failure("Photo dimensions are too large.");
 return size;
}
async function getItem(id:string,space:string){
 if(!validId(id))throw new Failure("Invalid photo.");
 const row=check(await sb.from("media_items").select("*").eq("id",id).eq("space_id",space).maybeSingle());
 if(!row)throw new Failure("Photo is unavailable.",404);return row;
}
Deno.serve(async req=>{
 if(req.method==="OPTIONS")return new Response(null,{headers:cors});
 if(req.method!=="POST")return json({error:"Use POST."},405);
 try{
  const auth=await identify(req);
  const isUpload=new URL(req.url).searchParams.get("action")==="upload";
  const raw=await bounded(req,isUpload?2250000:16384);
  if(isUpload){
   const form=await new Response(raw,{headers:{"Content-Type":req.headers.get("content-type")??""}}).formData();
   const id=form.get("id"),space=form.get("space"),taskId=form.get("task")||null,caption=form.get("caption")??"";
   const photo=form.get("photo"),thumb=form.get("thumbnail");
   if(!validId(id)||!validId(space)||(taskId!==null&&!validId(taskId))||typeof caption!=="string"||caption.length>300||!(photo instanceof File)||!(thumb instanceof File))throw new Failure("Invalid photo request.");
   await member(space,auth);
   const account=await firestore(`accounts/${auth.uid}`,auth.token,true);
   const plus=account.tier==="plus"&&(account.founderGrant===true||account.entitlementSource==="founder"||!account.subscriptionExpiresAt||new Date(account.subscriptionExpiresAt).getTime()>Date.now());
   const task=taskId?await firestore(`spaces/${space}/tasks/${taskId}`,auth.token):null;
   if(task&&task.creatorUid!==auth.uid&&task.ownerUid!==auth.uid)throw new Failure("Only the task creator or responsible person can attach a photo.",403);
   const bytes=new Uint8Array(await photo.arrayBuffer()),thumbnail=new Uint8Array(await thumb.arrayBuffer());
   const dimensions=jpeg(bytes,2000000,1600);jpeg(thumbnail,200000,320);
   const hashInput=new Uint8Array(bytes.length+thumbnail.length);hashInput.set(bytes);hashInput.set(thumbnail,bytes.length);
   const digest=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",hashInput))).map(b=>b.toString(16).padStart(2,"0")).join("");
   const row=check(await sb.rpc("reserve_media",{p:{id,uid:auth.uid,space,task:taskId,caption,digest,bytes:bytes.length+thumbnail.length,...dimensions,source:"shared",plus}}));
   if(row.state==="ready")return json({item:row});
   const prefix=`${space}/${auth.uid}/${id}`;
   check(await bucket.upload(`${prefix}/photo.jpg`,bytes,{contentType:"image/jpeg",upsert:true}));
   check(await bucket.upload(`${prefix}/thumb.jpg`,thumbnail,{contentType:"image/jpeg",upsert:true}));
   // Recheck authorization after upload; a concurrent removal must not publish.
   await member(space,auth);
   const current=taskId?await firestore(`spaces/${space}/tasks/${taskId}`,auth.token):null;
   const item=check(await sb.rpc("finish_media",{p_id:id,p_uid:auth.uid,p_published:!current||current.status==="completed"?new Date().toISOString():null,p_title:current?.status==="completed"?current.title:null,p_completed:current?.status==="completed"?current.ownerUid:null,p_plus:plus}));
   return json({item});
  }
  const body=JSON.parse(new TextDecoder().decode(raw));const space=body.space;
  await member(space,auth);
  if(body.action==="list"){
   const offset=Number(body.offset??0);if(!Number.isInteger(offset)||offset<0||offset>10000)throw new Failure("Invalid page.");
   const rows=check(await sb.from("media_items").select("*").eq("space_id",space).eq("state","ready").order("created_at",{ascending:false}).order("id").range(offset,offset+49));
   for(const taskId of new Set(rows.filter((r:any)=>r.task_id && !r.published_at).map((r:any)=>r.task_id))) {
    const completion=await firestore(`spaces/${space}/taskCompletions/${taskId}`,auth.token,true);
    if(completion.completedAt) {
     check(await sb.from("media_items").update({published_at:completion.completedAt,task_title:completion.title,completed_by:completion.ownerUid}).eq("space_id",space).eq("task_id",taskId).eq("state","ready").is("published_at",null));
     for(const row of rows) if(row.task_id===taskId && !row.published_at) Object.assign(row,{published_at:completion.completedAt,task_title:completion.title,completed_by:completion.ownerUid});
    }
   }
   return json({items:rows,nextOffset:rows.length===50?offset+50:null});
  }
  if(body.action==="publishTask"){
   if(!validId(body.task))throw new Failure("Invalid task.");
   const task=await firestore(`spaces/${space}/tasks/${body.task}`,auth.token);
   if(task.status!=="completed")throw new Failure("Finish the task first.");
   check(await sb.from("media_items").update({published_at:task.completedAt??new Date().toISOString(),task_title:task.title,completed_by:task.ownerUid}).eq("space_id",space).eq("task_id",body.task).eq("state","ready").is("published_at",null));
   return json({ok:true});
  }
  let row;
  try {row=await getItem(body.id,space);} catch(e) {
   if(body.action==='delete' && e instanceof Failure && e.status===404)return json({ok:true});
   throw e;
  }
  if(body.action==="delete"){
   if(row.uploader_uid!==auth.uid)throw new Failure("Only the uploader can remove this photo.",403);
   if(row.state==="deleted")return json({ok:true});
   check(await sb.from("media_items").update({state:"deleting"}).eq("id",row.id));
   const prefix=`${space}/${auth.uid}/${row.id}`;
   check(await bucket.remove([`${prefix}/photo.jpg`,`${prefix}/thumb.jpg`]));
   check(await sb.from("media_items").update({state:"deleted"}).eq("id",row.id));
   return json({ok:true});
  }
  if(body.action==="download"){
   if(row.state!=="ready")throw new Failure("Photo is unavailable.",404);
   const kind=body.thumbnail===true?"thumb":"photo";
   const blob=check(await bucket.download(`${space}/${row.uploader_uid}/${row.id}/${kind}.jpg`));
   return new Response(blob,{headers:{...cors,"Content-Type":"image/jpeg","X-Content-Type-Options":"nosniff"}});
  }
  throw new Failure("Unknown photo action.");
 }catch(error){
  if(error instanceof Failure)return json({error:error.message},error.status);
  // Never expose tokens, database details or stack traces to the client/log.
  if(error instanceof SyntaxError)return json({error:"Invalid request."},400);
  return json({error:"Could not finish this photo request. Sign in again or retry shortly."},503);
 }
});
